version: "3.7"
services:
  db:
    container_name: mysql
    image: mysql:8.0.19
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dblog
      MYSQL_ROOT_PASSWORD: Root@123
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  api:
    container_name: api
    build:
      dockerfile: "./Dockerfile-api"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  dumper:
    container_name: dumper
    build:
      dockerfile: "./Dockerfile-dumper"
    restart: always
    depends_on:
      - db