##
## build
##
FROM golang:1.18-buster AS build

WORKDIR /app

COPY ./ ./

RUN go mod download

WORKDIR ./cmd/api
RUN go build -o /api

##
## deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /api /api

USER nonroot:nonroot

ENTRYPOINT ["/api"]