##
## build
##
FROM golang:1.18-buster AS build

WORKDIR /app

COPY ./ ./

RUN go mod download

WORKDIR ./cmd/dumper
RUN go build -o /dumper

##
## deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /dumper /dumper
COPY --from=build /app/golang.log /

USER nonroot:nonroot

ENTRYPOINT ["/dumper"]